### ISSUE TITLE
TypeError: Cannot read property '_reject' of undefined

### ISSUE THREAD

**Issue by topliceanu** [burstable/node-beanstalkd-worker#4]
```

**Comment by topliceanu** [comment]
I figure out what the problem was by enabling `DEBUG=*`:

```
Sun, 19 Nov 2017 20:28:16 GMT beanstalkd-worker:webhooks reserve error TimeoutError: timed out connecting to beanstalkd (10000ms)
/home/me/node_modules/bluebird/js/main/promise.js:783
        promise._reject(value, carriedStackTrace);
                ^

TypeError: Cannot read property '_reject' of undefined
    at Promise._settlePromiseAt (/home/me/node_modules/bluebird/js/main/promise.js:783:17)
    at Promise._settlePromises (/home/me/node_modules/bluebird/js/main/promise.js:884:14)
    at Async._drainQueue (/home/me/node_modules/bluebird/js/main/async.js:98:12)
    at Async._drainQueues (/home/me/node_modules/bluebird/js/main/async.js:103:10)
    at Async.drainQueues (/home/me/node_modules/bluebird/js/main/async.js:37:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
Any way to catch and handle these errors

**Comment by mickhansen** [comment]
Doesn't look like the code properly exposes connection errors at the moment
